version: '3'
services:
    back:
        image: pierraad/gp-lp-dam-flexsante:back-latest
        environment:
            - DATABASE_URL=mongodb://db:27018/flexsante
        ports:
            - '3000:3000'
        depends_on:
            - db
        volumes:
            - /usr/src/back/node_modules
        networks:
            - flexsante-network

    db:
        image: mongo:latest
        command: mongod --port 27018
        ports:
            - '27018:27018'
        volumes:
            - dbdata:/data/db
        networks:
            - flexsante-network

    web:
        image: pierraad/gp-lp-dam-flexsante:front-latest
        ports:
            - 4000:4000
        volumes:
            - /usr/src/web/node_modules
        networks:
            - flexsante-network
        depends_on:
            - back

volumes:
    dbdata:

networks:
    flexsante-network:
