version: '3'
services:
    back:
        build: 
            context: ./back
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=mongodb://db:27018/flexsante
        ports:
            - '3124:3000'
        depends_on:
            - db
        volumes:
            - /usr/src/back/node_modules
        networks:
            - flexsante-network

    db:
        image: mongo:latest
        command: mongod --port 27018
        ports:
            - '27018:27018'
        volumes:
            - dbdata:/data/db
        networks:
            - flexsante-network

    web:
        build: 
            context: ./front
            dockerfile: Dockerfile
        ports:
            - 4124:4000
        volumes:
            - /usr/src/web/node_modules
        networks:
            - flexsante-network
        depends_on:
            - back

volumes:
    dbdata:

networks:
    flexsante-network:
