name: CI-Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DATABASE_URL_TEST: "mongodb://localhost:27017/flexsante-test"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./back

    strategy:
      matrix:
        mongodb-version: [4.4]

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.17.0"
      - name: Install dependencies
        run: npm install
      - name: Run test
        env:
          DATABASE_URL_TEST: "mongodb://localhost:27017/flexsante-test"
        run: npm run test