name: CI-Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    default:
      run: 
        working-directory: ./back

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.17.0"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test