name: Deploy on server

on:
  workflow_run:
    workflows: ["Publish docker"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook Action
      uses: joelwmale/webhook-action@2.1.0
      with:
        url: http://217.160.51.173:9000/hooks/FlexSante
        insecure: true

