name: Deploy on server

on:
  workflow_run:
    workflows: ["Publish docker"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v2
      with:
        webhook_url: http://217.160.51.173:9000/hooks/FlexSante
        webhook_secret: FlexFlex
