name: Deploy on server

on:
  workflow_run:
    workflows: ["Publish docker"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v2
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        verbose: true
