name: Publish docker

on:
  push:
    branches:
      - master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: front
          file: front/Dockerfile
          push: true
          tags: pierraad/gp-lp-dam-flexsante:front-latest
      -
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: back
          file: back/Dockerfile
          push: true
          tags: pierraad/gp-lp-dam-flexsante:back-latest
